### ISSUE TITLE
Pagination Conflict Between Two Tables on the Same Dashboard

### ISSUE THREAD

**Issue by gasner** [whitespacecode/nova-table-card#3]
Description:
There's a conflict with pagination when adding two components to the same dashboard in Laravel Nova. Changing the page on one table causes the other table to display the same data, as if they are sharing the same state.

Steps to reproduce:

Add two tables from the package to the same dashboard.
Configure both tables to use pagination.
Navigate to a different page on one of the tables.
Observe that the second table's data gets overwritten with the first table's data.
Expected Behavior:
Each table should maintain its state and pagination independently without affecting the other.

Actual Behavior:
Changing the page in one table updates the data in the other table, causing them to display the same content.

Environment:

Laravel Nova Version:4.0
Package Version: 1.0.4
Laravel Version: 10.0
PHP Version: 8.1

**Comment by whitespacecode** [comment]
Hi @gasner,

I am able to reproduce the issue and will look into it!

**Comment by whitespacecode** [comment]
@gasner 
This should be fixed in the latest release [v1.0.5](https://github.com/whitespacecode/nova-table-card/releases/tag/1.0.5)

Please check the [documentation](https://github.com/whitespacecode/nova-table-card#multiple-tablecards-with-pagination-per-page) for how to add multiple pagination instances on the same page

**Comment by gasner** [comment]
Thanks
